### ISSUE TITLE
Build is failing on Digital Ocean

### ISSUE THREAD

**Issue by ryan3738** [ryan3738/bellingham3d-backend#11]
# Error code on digital ocean

`Error: error:0308010C:digital envelope routines::unsupported
[2021-11-24 23:11:05]     at new Hash (node:internal/crypto/hash:67:19)
[2021-11-24 23:11:05]     at Object.createHash (node:crypto:130:10)
[2021-11-24 23:11:05]     at BulkUpdateDecorator.hashFactory (/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
[2021-11-24 23:11:05]     at BulkUpdateDecorator.update (/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
[2021-11-24 23:11:05]     at /workspace/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
[2021-11-24 23:11:05]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2021-11-24 23:11:05]     at runNextTicks (node:internal/process/task_queues:65:3)
[2021-11-24 23:11:05]     at processImmediate (node:internal/timers:437:9) {
[2021-11-24 23:11:05]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[2021-11-24 23:11:05]   library: 'digital envelope routines',
[2021-11-24 23:11:05]   reason: 'unsupported',
[2021-11-24 23:11:05]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[2021-11-24 23:11:05] }`

**Comment by ryan3738** [comment]
This hashing algorithm is no longer supported in Node 17.

**Comment by ryan3738** [comment]
Force node to version 16.13 until this issue is resolved.
